### ISSUE TITLE
Stabilize aarch64 features

### ISSUE THREAD

**Issue by zone117x** [Nugine/simd#1]
The [arch::is_aarch64_feature_detected!](https://doc.rust-lang.org/stable/std/arch/macro.is_aarch64_feature_detected.html) feature has been stabilized as of rust 1.60.0: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1600-2022-04-07

And armv8 neon intrinsics for aarch64 are stabilized as of rust 1.59.0: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1590-2022-02-24

The hex simd features in particular should be possible to use without the unstable flag. 

Awesome work on this library btw, very useful!

**Comment by Nugine** [comment]
Thanks. I will stabilize aarch64 features in v0.6.0 updates after a few days.

**Comment by Nugine** [comment]
The target feature "neon" is still unstable. We have to wait for it. See https://github.com/rust-lang/rust/issues/44839

**Comment by zone117x** [comment]
Ah that's disappointing, strange they would stabilize the other APIs without this one. Thanks anyway!

**Comment by Nugine** [comment]
The target feature has been stabilized since 1.61 (https://github.com/rust-lang/rust/pull/90621/).

I have no arm/aarch64 machines. The CI uses cross-rs to test correctness. Before landing aarch64 simd functions, I need to find a way to continuously confirm the performance.

**Comment by Nugine** [comment]
@zone117x 

I have managed to test aarch64 simd on my android phone (armv8). The performance looks good.

These providers have limited running time for free
+ <https://docs.travis-ci.com/user/multi-cpu-architectures/#multi-cpu-availability>
+ <https://circleci.com/docs/using-arm/>

i plan to setup arm tests and benches with CircleCI.

You are welcome to help with this project. There is no guide for local development yet. I will add some docs later.

For now, you can run this command

```bash
just bench static
```

The benchmark will save the results in a markdown file and print it.

Note that it may takes hours to run the whole benchmark.

The script depends on:
+ https://github.com/casey/just
+ https://github.com/sharkdp/bat

**Comment by zone117x** [comment]
Thank you for the info!
If you're planning on adding arm runners to the CI, I'll just wait for that. But if running the bench is helpful to unblock this issue, then I'm happy to help, just let me know!

**Comment by Nugine** [comment]
Stabilized in commit 5a00b302498bc146111e06831f97f3db191a2882.

Further steps:
+ #20 

Benchmarks running on physical machines are more realistic than CI. It will be helpful if you could report the statistics.
