### ISSUE TITLE
support floating number

### ISSUE THREAD

**Issue by moyy** [Nugine/simd#32]
now vsimd support integer number only, but it in 3D math it represent floating number, please consider support it as possible ?

**Comment by Nugine** [comment]
目前的结构可以支持浮点操作，但 vsimd 的 API 随时有可能大改，你可能要冒着破坏性变更的风险来用它。

有几条路线可以考虑
1. std::simd (portable-simd) + multiversion。它生成的浮点运算应该没什么问题。缺点是要开 nightly。
2. [generic-simd](https://docs.rs/generic-simd)，操作基本齐全，但有些抽象可能生成次优的 asm。
3. 使用 std::arch，基本上直接对应 asm，缺点是 unsafe 和麻烦。
4. 为 vsimd 提交 PR，添加你需要的操作。

vsimd 的 SIMD128 和 SIMD256 是各平台 SIMD 操作的并集。当前平台不支持的操作会被条件编译为 unreachable，在运行时 panic。

**Comment by moyy** [comment]
谢谢答复。

我目前在看 rust [glam](https://github.com/bitshifter/glam-rs) 的 simd 实现，这个库 是 直接实现 vec3f / vec3d / vec4f, vec4d, 没有抽象，而且目前只支持 PC；所以 我这边 计划写个 trait 将 这些数据类型和操作 统一 起来；

目前在参考你这边的抽象思路，再次感谢；

**Comment by Nugine** [comment]
portable-simd 对某些特殊操作可能生成标量指令，或者次优的指令，原因有的在 rustc，有的在 LLVM。#7 列了两个例子。一般的整数和浮点运算应该没问题。

portable-simd 封装的是 safe 接口，鼓励使用高级抽象，有些写法可能不会被优化干净，写完用 [cargo asm](https://github.com/pacak/cargo-show-asm) 确认一下。

std::arch 给的是 SIMD 指令的 unsafe 函数封装，直接对应指令。

性能排序: $\text{std::simd} \le \text{std::arch} \le \text{inline asm}$。当优化生效时应该没有明显差距。

**Comment by Nugine** [comment]
由于短期内没有开放 vsimd 的计划，目前关闭该 issue
