### ISSUE TITLE
Return encode/decode size as part of encode/decode call

### ISSUE THREAD

**Issue by stevedw** [Nugine/simd#36]
Would it be possible to add a simple encode/decode method pair?

e.g:

encode_to_slice(source:&[u8],dest:&mut [u8])->Result(usize, Error)

decode_to_slice(source: &[u8], dest[&mut[u8])->Result(usize, Error)

so the caller does not need to call sizing additionally to find out how much was written. It just makes it a little more fluid to use.

This obviously assumes the dest buffers are large enough to hold the output (as with the other encode/decode methods)

**Comment by Nugine** [comment]
Current API (a bit different from v0.8):
https://github.com/Nugine/simd/blob/cf6cc4a0d835182e7b64ba8679423c3c2c76a198/crates/base64-simd/src/lib.rs#L227-L232

https://github.com/Nugine/simd/blob/cf6cc4a0d835182e7b64ba8679423c3c2c76a198/crates/base64-simd/src/lib.rs#L255-L262

The two methods return the written part of `dst`. So the caller can use the written part without `assume_init` or slice indexing. 

To get how much was written, a typical style is appending `.unwrap().len()`. I don't think it worths a pair of new APIs. Can you show some use cases?

Moreover, you can wrap the crate with your favourite signature. (Recommanded!)

```rust
use base64_simd::{AsOut, Error};

pub fn encode(src: &[u8], dst: &mut [u8]) -> Result<usize, Error> {
    base64_simd::STANDARD.encode(src, dst.as_out()).map(|s|s.len())
}
```

**Comment by stevedw** [comment]
The use case I mostly have is to write many base64 encoded and decoded parts into larger buffers as fragments, so the entire buffer may consists of
dst = someLargebuffer

encode(srs.dest);
addheader(dst)
encode(src2,dst)
addheader(dst)

etc

the reverse for the decode is also true as the decoded happen form variable size inputs into a larger working buffer which then is used to transcribe into a different format. So the dst buffers in each decode just acts as a working buf for a larger set of data.

I agree that  if as you say ```&'d mut [u8]``` is a slice of the out buffer containing just the written bytes I can just take the len of that (its not clear from the docs that this is the case)

Its just that in the cases I have, the return buffer and constructing the Out is no use to me and just adds overhead in the call paths, as I need to use the return size as a pointer into the larger working buffer anyway. A simple return size is more useful.

If you think its not worth it, I understand and I can work round it.

Thanks for the library anyway, its very useful.

**Comment by stevedw** [comment]
ok - thanks - just to say I am restricted to using base64 by the downstream specifications so unfortunately I am looking to optimise the path and allocate as little as possible with that restriction in mind.
